### PR TITLE
Change the PluginEvasion class to public so that Remove can be called. fix: can not login google

### PR DESCRIPTION
**Pull request by namilkimfree**
Pr:  
Change the PluginEvasion class to public so that Remove can be called from outside.

related links: https://github.com/berstend/puppeteer-extra/issues/668

stealth Plugin detected on [Gmail&Google] after Login page

reflects the issue.

Info:
To log in to google

  ```
          var plugin = new StealthPlugin();
            plugin.RemoveEvasionByType<PluginEvasion>();
            plugin.RemoveEvasionByType<ContentWindow>();
```

screenshot 

image

… from outside

Package version up lasted: PuppeteerSharp, RestSharp

---
Fix google can not login issue

Updated puppeteer-sharp version 7.1.0. whereby the issue below seems to have been fixed automatically.
AnonymizeUaPlugin not working in puppetsharp 7.1.0

fix: #39  #24 #40

### CODE REVIEW

**Comment by namilkimfree** [comment]
hello  @Overmiind  

could be check please?

**Comment by euunit** [comment]
Would be great if someone would review it.

**Comment by namilkimfree** [comment]
https://www.nuget.org/packages/PuppeteerExtraSharp-Custom/
 
I have deployed a custom version for my use.

**Comment by Overmiind** [comment]
Was fixed by https://github.com/Overmiind/Puppeteer-sharp-extra/pull/49

**Comment by daniil-steperev** [comment]
@namilkimfree, thank you very much for your solution! This bug has been driving me crazy all day :))

**Pull request closed without merging**
